version: '3'

services:
  backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - database

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '5173:5173'
  #   volumes:
  #     - .:/client
  #     - .:/client/node_modules

  #   depends_on:
  #     - backend

  database:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
volumes:
  dbdata:
